### ISSUE TITLE
How to convert local tests to Web Platform Tests?

### ISSUE THREAD

**Issue by guest271314** [foolip/testing-in-standards#3]
Have composed several tests relevant to Web Speech API https://github.com/w3c/web-platform-tests/issues/8795 and SSML parsing https://github.com/w3c/web-platform-tests/issues/8712, https://github.com/guest271314/SpeechSynthesisSSMLParser. 

What is the canonical approach to incorporate these tests into the respective Web Platform Tests folder, or create the folder (SSML)?

Would the tests (manual) be useful for the Web Platform Tests repository?

(Asked same question at http://irc.w3.org/ #testing though did not get a response before submitting this issue.)

**Comment by foolip** [comment]
Manual tests are fine if nothing else is possible, just name them foo-manual.html. https://github.com/w3c/web-platform-tests/tree/master/speech-api is the directory for Web Speech API.

As for SSML, it looks like Chromium doesn't support that, does any implementation?

**Comment by guest271314** [comment]
Browsers do not come shipped with an SSML parser that am aware of. Tried to find such existing code https://softwareengineering.stackexchange.com/questions/362911/how-to-extract-ssml-parsing-code-of-espeak-to-implement-ssml-parsing-at-speechsy before began composing the parser in JavaScript. The code at https://github.com/guest271314/SpeechSynthesisSSMLParser implements an SSML parser (the the point have reached so far) following the [specification](https://www.w3.org/TR/speech-synthesis11/) using JavaScript. 

The concern that have is the use of arrow functions, `const`, etc. within the current code. If that is not an issue will create the "ssml" folder at Web Platform Tests and include the tests that have completed so far.

**Comment by guest271314** [comment]
Browsers do not come shipped with an SSML parser that am aware of. Tried to find such existing code https://softwareengineering.stackexchange.com/questions/362911/how-to-extract-ssml-parsing-code-of-espeak-to-implement-ssml-parsing-at-speechsy before began composing the parser in JavaScript; see also https://stackoverflow.com/a/48504311/.

The code at https://github.com/guest271314/SpeechSynthesisSSMLParser implements an SSML parser (to the point have reached as to the standardized elements and attributes) following the [specification](https://www.w3.org/TR/speech-synthesis11/) using JavaScript. 

The concern that have is the use of arrow functions, `const`, etc. within the current code. If that is not an issue will create the "ssml" folder at Web Platform Tests and include the tests that have completed so far.

**Comment by foolip** [comment]
I was about to file an issue about SSML not being implemented, but used https://github.com/w3c/speech-api/issues/10 instead.

Since the spec doesn't actually say how it should work I don't know how to write tests for it, and more importantly, if nobody is inclined to implement it then the tests will just be failing forever.

**Comment by guest271314** [comment]
> Since the spec doesn't actually say how it should work

Not sure what you mean?

**Comment by foolip** [comment]
The spec doesn't spell out what test should be performed on the input to determine whether it is SSML or should be treated as plain text.

**Comment by guest271314** [comment]
Yes, that is unclear.

**Comment by guest271314** [comment]
> The spec doesn't spell out what test should be performed on the input to determine whether it is SSML or should be treated as plain text.

When re-reading the specification the requirement is spelled out

[5.2.3 SpeechSynthesisUtterance Attributes](https://w3c.github.io/speech-api/speechapi.html#utterance-attributes) 
>  or a complete, well-formed SSML document.
